
services:
  db:
    image: postgres:latest
    container_name: uchiha_container
    environment:
      POSTGRES_USER: uchiha_itachi
      POSTGRES_PASSWORD: sharingan
      POSTGRES_DB: uchiha_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uchiha_itachi -d uchiha_db"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data:
